-- 麻雀WELCOME 店舗備品発注アプリ専用テーブル
-- Supabase Dashboard > SQL Editor で一度だけ実行してください。

create table if not exists public.welcome_supply_orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  store text not null check (store in (
    '千葉店', '新小岩店', '大宮店', '日暮里店',
    '靖国通り店', '三宮店', '歌舞伎町店', '水道橋店'
  )),
  staff text not null,
  order_date date not null default current_date,
  delivery_type text not null default '通常（月末）'
    check (delivery_type in ('通常（月末）', '至急')),
  delivery_date date,
  card_quantity integer not null default 0 check (card_quantity >= 0),
  free_quantity integer not null default 0 check (free_quantity >= 0),
  set_quantity integer not null default 0 check (set_quantity >= 0),
  receipt_quantity integer not null default 0 check (receipt_quantity >= 0),
  handwritten_male_quantity integer not null default 0 check (handwritten_male_quantity >= 0),
  handwritten_female_quantity integer not null default 0 check (handwritten_female_quantity >= 0),
  name_tags jsonb not null default '[]'::jsonb,
  notes text not null default '',
  created_at timestamptz not null default now()
);

create index if not exists welcome_supply_orders_store_created_idx
  on public.welcome_supply_orders (store, created_at desc);

alter table public.welcome_supply_orders enable row level security;

drop policy if exists "welcome_orders_read" on public.welcome_supply_orders;
drop policy if exists "welcome_orders_insert" on public.welcome_supply_orders;

create policy "welcome_orders_read"
  on public.welcome_supply_orders for select to anon using (true);

create policy "welcome_orders_insert"
  on public.welcome_supply_orders for insert to anon with check (true);

grant select, insert on public.welcome_supply_orders to anon;
grant usage, select on sequence public.welcome_supply_orders_id_seq to anon;
