-- 麻雀WELCOME 名札・サービス券発注アプリ専用テーブル
-- Supabase Dashboard > SQL Editor で一度だけ実行してください。

create table if not exists public.welcome_supply_orders (
  id bigint generated by default as identity primary key,
  order_id text not null unique,
  store text not null check (store in (
    '千葉店', '新小岩店', '大宮店', '日暮里店',
    '靖国通り店', '三宮店', '歌舞伎町店', '水道橋店'
  )),
  staff text not null,
  order_date date not null default current_date,
  delivery_type text not null default '通常（月末）'
    check (delivery_type in ('通常（月末）', '至急')),
  delivery_date date,
  card_quantity integer not null default 0 check (card_quantity >= 0),
  free_quantity integer not null default 0 check (free_quantity >= 0),
  set_quantity integer not null default 0 check (set_quantity >= 0),
  receipt_quantity integer not null default 0 check (receipt_quantity >= 0),
  handwritten_male_quantity integer not null default 0 check (handwritten_male_quantity >= 0),
  handwritten_female_quantity integer not null default 0 check (handwritten_female_quantity >= 0),
  name_tags jsonb not null default '[]'::jsonb,
  notes text not null default '',
  status text not null default '未手配'
    check (status in ('未手配', '手配中', '完了')),
  completed_at timestamptz,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

alter table public.welcome_supply_orders
  add column if not exists status text not null default '未手配',
  add column if not exists completed_at timestamptz,
  add column if not exists updated_at timestamptz not null default now();

create index if not exists welcome_supply_orders_store_created_idx
  on public.welcome_supply_orders (store, created_at desc);

alter table public.welcome_supply_orders enable row level security;

drop policy if exists "welcome_orders_read" on public.welcome_supply_orders;
drop policy if exists "welcome_orders_insert" on public.welcome_supply_orders;

create policy "welcome_orders_read"
  on public.welcome_supply_orders for select to anon using (true);

create policy "welcome_orders_insert"
  on public.welcome_supply_orders for insert to anon with check (true);

grant select, insert on public.welcome_supply_orders to anon;
grant usage, select on sequence public.welcome_supply_orders_id_seq to anon;

create extension if not exists pgcrypto;

create table if not exists public.welcome_admin_settings (
  id text primary key default 'main',
  pin_hash text not null
);

alter table public.welcome_admin_settings enable row level security;
revoke all on public.welcome_admin_settings from anon;

-- 次の値は設定時に実際の管理PINへ置き換えます。
insert into public.welcome_admin_settings (id, pin_hash)
values ('main', extensions.crypt('__ADMIN_PIN__', extensions.gen_salt('bf')))
on conflict (id) do update set pin_hash = excluded.pin_hash;

create or replace function public.welcome_admin_pin_is_valid(p_pin text)
returns boolean
language sql
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.welcome_admin_settings
    where id = 'main' and pin_hash = extensions.crypt(p_pin, pin_hash)
  );
$$;

create or replace function public.welcome_admin_list_orders(p_pin text)
returns setof public.welcome_supply_orders
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.welcome_admin_pin_is_valid(p_pin) then
    raise exception 'invalid admin pin';
  end if;
  return query
    select * from public.welcome_supply_orders
    order by created_at desc
    limit 500;
end;
$$;

create or replace function public.welcome_admin_update_status(
  p_pin text,
  p_order_id text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.welcome_admin_pin_is_valid(p_pin) then
    raise exception 'invalid admin pin';
  end if;
  if p_status not in ('未手配', '手配中', '完了') then
    raise exception 'invalid status';
  end if;

  update public.welcome_supply_orders
  set status = p_status,
      completed_at = case when p_status = '完了' then coalesce(completed_at, now()) else null end,
      updated_at = now()
  where order_id = p_order_id;
end;
$$;

revoke all on function public.welcome_admin_pin_is_valid(text) from public;
grant execute on function public.welcome_admin_list_orders(text) to anon;
grant execute on function public.welcome_admin_update_status(text, text, text) to anon;

-- 発注時の本部メール通知
-- 次の2つの値は設定時に実際のWebアプリURLと通知連携キーへ置き換えます。
create extension if not exists pg_net with schema extensions;

create or replace function public.notify_welcome_order_email()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  perform net.http_post(
    url := '__MAIL_WEBHOOK_URL__',
    headers := '{"Content-Type":"application/json"}'::jsonb,
    body := jsonb_build_object(
      'token', '__MAIL_WEBHOOK_TOKEN__',
      'order', to_jsonb(new)
    )
  );
  return new;
end;
$$;

drop trigger if exists welcome_order_email_notification
  on public.welcome_supply_orders;

create trigger welcome_order_email_notification
after insert on public.welcome_supply_orders
for each row execute function public.notify_welcome_order_email();
